-- File auto generated by purescript-bridge! --
module Gonimo.Server.State.Types where

import Prim (Int)

import Data.Generic (class Generic)


data SessionId =
    SessionId Int

derive instance genericSessionId :: Generic SessionId

