-- File auto generated by purescript-bridge! --
module Gonimo.Server.Types where

import Gonimo.Types (Secret)
import Prim (String)

import Data.Generic (class Generic)


data AuthToken =
    GonimoSecret Secret

derive instance genericAuthToken :: Generic AuthToken

data Coffee =
    Tea 

derive instance genericCoffee :: Generic Coffee

data InvitationDelivery =
    EmailInvitation String
  | OtherDelivery 

derive instance genericInvitationDelivery :: Generic InvitationDelivery

